# Debian slim + 21jdk
FROM openjdk:21-jdk-slim

# Continue with your application deployment
RUN mkdir /opt/app
COPY /build/libs/patient-domain-service-0.0.1-SNAPSHOT.jar /opt/app
CMD ["java", "-Dcom.sun.management.jmxremote", "-Dcom.sun.management.jmxremote.rmi.port=7012", "-Dcom.sun.management.jmxremote.port=7012", "-Dcom.sun.management.jmxremote.authenticate=false", "-Dcom.sun.management.jmxremote.ssl=false", "-Djava.rmi.server.hostname=127.0.0.1", "-XX:NativeMemoryTracking=summary","-jar", "/opt/app/patient-domain-service-0.0.1-SNAPSHOT.jar"]

# "-XX:MaxHeapSize=805306368", "-XX:+UseZGC", "-XX:+UseCompressedOops",